#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mkdir -p constant/triSurface

# copy hull surface from resources folder
cp QHullOrigin.stl constant/triSurface/

runApplication surfaceFeatureExtract

runApplication blockMesh

for i in 1 2 3 4 5 6
do
    runApplication -s "$i" \
        topoSet -dict system/topoSetDict.${i}

    runApplication -s "$i" \
        refineMesh -dict system/refineMeshDict -overwrite
done

runApplication snappyHexMesh -overwrite

runApplication checkMesh

touch open.foam

restore0Dir

runApplication setFields

# runApplication decomposePar
runParallel -s decompose redistributePar -decompose

runParallel renumberMesh -overwrite

runParallel $(getApplication)

# runApplication reconstructPar
runParallel -s reconstruct redistributePar -reconstruct

#------------------------------------------------------------------------------
